##############################################################################
#
# Copyright 2021 Autodesk, Inc. All rights reserved.
#
# Use of this software is subject to the terms of the Autodesk license
# agreement provided at the time of installation or download, or which
# otherwise accompanies this software in either electronic or hard copy form.
#
##############################################################################

name: Build-Documentation

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [macOS-10.15, windows-2019, ubuntu-20.04]
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo scripts/install_deps.sh

    - name: Build
      run: scripts/build_documentation.sh