name: Build-Documentation

on: [push]

jobs:
  build:
    runs-on: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo scripts/install_deps.sh

    - name: Build Documentation
      run: scripts/build_documentation.sh
